# Generated by Claude Code 2026-01-05
# Performance optimization: Add critical indexes for checkout queries

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0086_merge_20251212_0956"),
    ]

    operations = [
        # ============================================================================
        # CHECKOUT MODEL INDEXES
        # ============================================================================

        # Composite index for user's recent checkouts
        # Used in: Cart recovery, finding user's active cart
        # Impact: Faster cart loading for returning customers
        migrations.AddIndex(
            model_name="checkout",
            index=models.Index(
                fields=["user_id", "last_change"],
                name="checkout_user_recent_idx",
            ),
        ),

        # Composite index for channel checkout monitoring
        # Used in: Admin dashboard, channel-specific cart analytics
        migrations.AddIndex(
            model_name="checkout",
            index=models.Index(
                fields=["channel_id", "last_change"],
                name="checkout_ch_recent_idx",
            ),
        ),

        # Composite index for guest checkout recovery
        # Used in: Guest cart recovery by email
        migrations.AddIndex(
            model_name="checkout",
            index=models.Index(
                fields=["email", "channel_id"],
                name="checkout_email_ch_idx",
            ),
        ),

        # Partial index for abandoned checkouts
        # Excludes in-progress completions, used for abandoned cart campaigns
        # Reduces index size by excluding checkouts being completed
        migrations.AddIndex(
            model_name="checkout",
            index=models.Index(
                fields=["last_change", "channel_id"],
                name="checkout_abandoned_idx",
                condition=Q(completing_started_at__isnull=True),
            ),
        ),

        # Index for stuck/locked checkout detection
        # Used in: Finding checkouts where completion started but didn't finish
        migrations.AddIndex(
            model_name="checkout",
            index=models.Index(
                fields=["completing_started_at", "last_change"],
                name="checkout_completing_idx",
            ),
        ),
    ]
