# Generated by Django 5.2.8 on 2025-12-31 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0087_merge_20250630_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='flash_sale_label',
            field=models.CharField(blank=True, default='', help_text="Label to display for the flash sale (e.g., 'Flash Deal', 'Lightning Sale')", max_length=100),
        ),
        migrations.AddField(
            model_name='promotion',
            name='is_flash_sale',
            field=models.BooleanField(default=False, help_text='Whether this is a time-limited flash sale'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='sold_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of items sold at flash sale price'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='stock_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of items available at flash sale price', null=True),
        ),
    ]
