# Generated by Django 5.2.8 on 2026-01-02 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0095_repopulate_user_number_of_orders'),
        ('order', '0219_merge_20251212_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatWidgetSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('provider', models.CharField(choices=[('internal', 'Internal Chat'), ('tawk_to', 'Tawk.to'), ('intercom', 'Intercom'), ('zendesk', 'Zendesk'), ('crisp', 'Crisp'), ('custom', 'Custom')], default='internal', max_length=20)),
                ('widget_id', models.CharField(blank=True, max_length=255)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('position', models.CharField(choices=[('bottom_right', 'Bottom Right'), ('bottom_left', 'Bottom Left')], default='bottom_right', max_length=20)),
                ('primary_color', models.CharField(default='#0066cc', max_length=7)),
                ('welcome_message', models.TextField(default='Hi! How can we help you today?')),
                ('offline_message', models.TextField(default="We're currently offline. Leave a message!")),
                ('show_on_mobile', models.BooleanField(default=True)),
                ('delay_seconds', models.PositiveIntegerField(default=3)),
                ('custom_script_url', models.URLField(blank=True)),
                ('custom_config', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chat Widget Settings',
                'verbose_name_plural': 'Chat Widget Settings',
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(blank=True, max_length=255)),
                ('visitor_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for Agent'), ('active', 'Active'), ('closed', 'Closed')], default='waiting', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_chat_sessions', to='account.user')),
                ('order', models.ForeignKey(blank=True, help_text='Related order if chat is about a specific order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='order.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='account.user')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sender_type', models.CharField(choices=[('user', 'User'), ('agent', 'Agent'), ('bot', 'Bot'), ('system', 'System')], max_length=10)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('attachment_url', models.URLField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages_sent', to='account.user')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', 'status'], name='chat_chatse_user_id_7162c5_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['agent', 'status'], name='chat_chatse_agent_i_d229bd_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['status', 'started_at'], name='chat_chatse_status_90ccca_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'is_read'], name='chat_chatme_session_60678a_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'created_at'], name='chat_chatme_session_70d41b_idx'),
        ),
    ]
