# Generated by Claude Code 2026-01-05
# Performance optimization: Add critical indexes for order queries

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0219_merge_20251212_0955"),
    ]

    operations = [
        # ============================================================================
        # ORDER MODEL INDEXES (CRITICAL)
        # ============================================================================

        # Composite index for user order history
        # Used in: Customer order history pages (most common query)
        # Impact: 50-70% faster order history queries
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["user_id", "created_at"],
                name="order_user_created_idx",
            ),
        ),

        # Composite index for admin order management
        # Used in: Admin order lists filtered by channel and status
        # Impact: 40-50% faster admin order queries
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["channel_id", "status", "created_at"],
                name="order_ch_status_idx",
            ),
        ),

        # Composite index for fulfillment filtering
        # Used in: ready_to_fulfill() queryset and fulfillment operations
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["status", "charge_status", "total_gross_amount"],
                name="order_fulfill_filter_idx",
            ),
        ),

        # Partial index for non-draft orders
        # Excludes draft orders from index (reduces size by 5-10%)
        # Used in: non_draft() queryset - the most common filter
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["channel_id", "created_at"],
                name="order_non_draft_idx",
                condition=~Q(status="draft"),
            ),
        ),

        # Index for guest order lookups by email
        # Used in: Guest checkout order retrieval
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["channel_id", "user_email"],
                name="order_ch_email_idx",
            ),
        ),

        # Partial index for active orders needing fulfillment
        # Excludes completed/cancelled orders (reduces size significantly)
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["created_at"],
                name="order_active_idx",
                condition=Q(status__in=["unfulfilled", "partially_fulfilled"]),
            ),
        ),

        # ============================================================================
        # ORDERLINE MODEL INDEXES
        # ============================================================================

        # Composite index for variant lookups in orders
        # Used in: Reorder functionality, variant order history
        migrations.AddIndex(
            model_name="orderline",
            index=models.Index(
                fields=["order_id", "variant_id"],
                name="orderline_order_var_idx",
            ),
        ),

        # Composite index for product sales analytics
        # Used in: resolve_report_product_sales() - sales over time
        # Impact: Essential for analytics and reporting
        migrations.AddIndex(
            model_name="orderline",
            index=models.Index(
                fields=["variant_id", "created_at"],
                name="orderline_var_date_idx",
            ),
        ),

        # Index for shipping requirement checks
        # Used in: Order.is_shipping_required() method
        migrations.AddIndex(
            model_name="orderline",
            index=models.Index(
                fields=["order_id", "is_shipping_required"],
                name="orderline_shipping_idx",
            ),
        ),

        # Index for product type analytics
        # Used in: Sales reports by product type
        migrations.AddIndex(
            model_name="orderline",
            index=models.Index(
                fields=["product_type_id", "created_at"],
                name="orderline_type_date_idx",
            ),
        ),
    ]
