mutation TokenCreate($email: String!, $password: String!) {
	tokenCreate(email: $email, password: $password) {
		token
		refreshToken
		errors {
			field
			message
			code
		}
		user {
			id
			email
			firstName
			lastName
			isActive
			isConfirmed
		}
	}
}

mutation AccountRegister($input: AccountRegisterInput!) {
	accountRegister(input: $input) {
		user {
			id
			email
			firstName
			lastName
		}
		errors {
			field
			message
			code
		}
	}
}

mutation TokenRefresh($refreshToken: String!) {
	tokenRefresh(refreshToken: $refreshToken) {
		token
		errors {
			field
			message
			code
		}
	}
}

mutation RequestPasswordReset($email: String!, $redirectUrl: String!, $channel: String!) {
	requestPasswordReset(email: $email, redirectUrl: $redirectUrl, channel: $channel) {
		errors {
			field
			message
			code
		}
	}
}

mutation SetPassword($token: String!, $email: String!, $password: String!) {
	setPassword(token: $token, email: $email, password: $password) {
		token
		refreshToken
		errors {
			field
			message
			code
		}
		user {
			id
			email
		}
	}
}

mutation ConfirmAccount($email: String!, $token: String!) {
	confirmAccount(email: $email, token: $token) {
		user {
			id
			email
			isConfirmed
		}
		errors {
			field
			message
			code
		}
	}
}

mutation SendConfirmationEmail($channel: String!, $redirectUrl: String!) {
	sendConfirmationEmail(channel: $channel, redirectUrl: $redirectUrl) {
		errors {
			field
			message
			code
		}
	}
}
