query OrderById($id: ID!) {
	order(id: $id) {
		id
		number
		status
		isPaid
		created
		lines {
			id
			productName
			variantName
			quantity
			thumbnail {
				url
			}
			totalPrice {
				gross {
					amount
					currency
				}
			}
		}
		subtotal {
			gross {
				amount
				currency
			}
		}
		shippingPrice {
			gross {
				amount
				currency
			}
		}
		total {
			gross {
				amount
				currency
			}
		}
		shippingAddress {
			firstName
			lastName
			streetAddress1
			streetAddress2
			city
			countryArea
			postalCode
			phone
			country {
				code
				country
			}
		}
		billingAddress {
			firstName
			lastName
			streetAddress1
			streetAddress2
			city
			countryArea
			postalCode
			phone
			country {
				code
				country
			}
		}
	}
}
