query SearchProducts(
	$search: String!
	$sortBy: ProductOrderField!
	$sortDirection: OrderDirection!
	$first: Int
	$after: String
	$last: Int
	$before: String
	$channel: String!
	$categories: [ID!]
	$minPrice: Float
	$maxPrice: Float
) {
	products(
		first: $first
		after: $after
		last: $last
		before: $before
		channel: $channel
		sortBy: { field: $sortBy, direction: $sortDirection }
		filter: { search: $search, categories: $categories, price: { gte: $minPrice, lte: $maxPrice } }
	) {
		totalCount
		edges {
			node {
				...ProductListItem
			}
			cursor
		}
		pageInfo {
			hasNextPage
			hasPreviousPage
			endCursor
			startCursor
		}
	}
}
