# Generated by Django 5.2.8 on 2026-01-02 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0095_repopulate_user_number_of_orders'),
        ('order', '0219_merge_20251212_0955'),
        ('product', '0202_category_product_category_tree_id_lf1e1'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter/X'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('linkedin', 'LinkedIn'), ('pinterest', 'Pinterest'), ('email', 'Email'), ('copy_link', 'Copy Link')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='product.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_shares', to='account.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductShareClick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_platform', models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('twitter', 'Twitter/X'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('linkedin', 'LinkedIn'), ('pinterest', 'Pinterest'), ('email', 'Email'), ('copy_link', 'Copy Link')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('converted_to_order', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='share_click_conversions', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_clicks', to='product.product')),
                ('share', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='social.productshare')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='productshare',
            index=models.Index(fields=['product', 'platform'], name='social_prod_product_7104d3_idx'),
        ),
        migrations.AddIndex(
            model_name='productshare',
            index=models.Index(fields=['product', 'created_at'], name='social_prod_product_3b34e5_idx'),
        ),
        migrations.AddIndex(
            model_name='productshare',
            index=models.Index(fields=['user', 'created_at'], name='social_prod_user_id_6f880c_idx'),
        ),
        migrations.AddIndex(
            model_name='productshareclick',
            index=models.Index(fields=['product', 'source_platform'], name='social_prod_product_f2d0ef_idx'),
        ),
        migrations.AddIndex(
            model_name='productshareclick',
            index=models.Index(fields=['converted_to_order'], name='social_prod_convert_d0aa25_idx'),
        ),
    ]
