# Generated by Django 5.2.8 on 2026-01-02 16:14

import django.db.models.deletion
import saleor.core.utils.json_serializer
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0095_repopulate_user_number_of_orders'),
        ('channel', '0027_channel_allow_legacy_gift_card_use'),
        ('product', '0202_category_product_category_tree_id_lf1e1'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('trigger_type', models.CharField(choices=[('any_drop', 'Alert on any price drop'), ('percentage', 'Alert when price drops by percentage'), ('target_price', 'Alert when price reaches target'), ('back_in_stock', 'Alert when product is back in stock')], default='any_drop', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('triggered', 'Triggered'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('original_price', models.DecimalField(decimal_places=3, help_text='Price when alert was created', max_digits=12)),
                ('target_price', models.DecimalField(blank=True, decimal_places=3, help_text='Target price for TARGET_PRICE alerts', max_digits=12, null=True)),
                ('target_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Target percentage drop for PERCENTAGE alerts', max_digits=5, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('notification_channels', models.JSONField(default=list, help_text='List of notification channels')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to='channel.channel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to='account.user')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to='product.productvariant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceAlertNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=3, max_digits=12)),
                ('new_price', models.DecimalField(decimal_places=3, max_digits=12)),
                ('drop_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('currency', models.CharField(max_length=3)),
                ('notification_channel', models.CharField(choices=[('email', 'Email'), ('push', 'Push Notification'), ('sms', 'SMS'), ('in_app', 'In-App Notification')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='pricealert.pricealert')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=3, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='channel.channel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='product.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='product.productvariant')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pricealert',
            index=models.Index(fields=['user', 'status'], name='pricealert__user_id_afa05c_idx'),
        ),
        migrations.AddIndex(
            model_name='pricealert',
            index=models.Index(fields=['product', 'status'], name='pricealert__product_a5c452_idx'),
        ),
        migrations.AddIndex(
            model_name='pricealert',
            index=models.Index(fields=['status', 'expires_at'], name='pricealert__status_34cd8a_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['product', 'channel', 'recorded_at'], name='pricealert__product_e4e9b1_idx'),
        ),
    ]
