# Generated by Claude Code 2026-01-05
# Performance optimization: Add critical indexes for user queries

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0095_repopulate_user_number_of_orders"),
    ]

    operations = [
        # ============================================================================
        # USER MODEL INDEXES
        # ============================================================================

        # Composite index for user authentication and admin lists
        # Used in: User authentication, active staff user queries
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_active", "is_staff", "email"],
                name="user_active_staff_idx",
            ),
        ),

        # Composite index for staff user lists
        # Used in: Staff management pages ordered by join date
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_staff", "date_joined"],
                name="user_staff_joined_idx",
            ),
        ),

        # Index for customer segmentation
        # Used in: Marketing queries finding high-value or active customers
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["number_of_orders", "date_joined"],
                name="user_orders_activity_idx",
            ),
        ),
    ]
